import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {AuthProvider} from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import { auth } from "@/auth";
import { JetBrains_Mono, Montserrat } from "next/font/google"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const jetBrainsMono = JetBrains_Mono({ 
  subsets: ['latin'],
  weight : ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrains-mono',
});
const montserrat = Montserrat({
  subsets : ["latin"],
  weight : ['100','200','300','400','500','600','700','800','900'],
  variable : '--font-montserrat'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <html lang="en" className="dark">
      <AuthProvider session={session}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased ${jetBrainsMono.variable} ${montserrat.variable} font-sans`}
        >
          <main>{children}</main>
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
